### ISSUE TITLE
create safe lookup table for attributes

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/meddle#1]
use-case: point to a file or set of files (e.g., shapefile collection) and extract the headers/attributes of the dataset. Create a table with those attributes and empty cells for the rest of the info to be filled out by hand. 

Probably a csv makes the most sense for this output. 

the "safe" part of this comes from doing a safe append to an existing table - so you don't wipe out your existing info if your dataset adds a column and you run this function again.

**Comment by berdaniera** [comment]
Does the safe append need to check if the attribute exists already? Or just append it to the csv (with something like `writeLines`)?

**Comment by jread-usgs** [comment]
Probably check if they exist, so you don't end up with duplicates of the same attribute (in which case the latter empty one would end up being used)

**Comment by jread-usgs** [comment]
I'll take this one
