### ISSUE TITLE
only replace list values when they exist?

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/meddle#31]
```r
meddle:::append_list_replace(list(dog='larry'), list(dog=NA))
$dog
[1] NA
```
But do we want this? `NA` or `""` are empty, and if we have values defined elsewhere, should we use them?

Use-case is when we are doing something like this:
```r
render("../4_data_release/in/metadata_site_points.yaml", "../4_data_release/out/site_points_shapefile.shp.xml", points_attr)
```
where points_attr has all of the attributes, but maybe some are defined in the yaml.

**Comment by aappling-usgs** [comment]
The first example you gave has the behavior I'd expect. My intuition for the second is that anything given in points_attr should override anything that came earlier in the list, or possibly that an error/warning should be given if anything is getting overridden. Are there cases when it wouldn't be feasible for the user to exclude values from points_attr that they didn't want to include in the metadata?

**Comment by jread-usgs** [comment]
Good point. 

I was working on this for the use-case above, where I do want the package to scrape the shapefile and list out the attributes so we can make sure all are covered, but also want to be able to fill in blank ones from the yaml and have those values stick. How about 

```r
append_list_replace <- function(list0, ..., replace.empty=TRUE){
}
``` 
as the signature instead? (just adds `replace.empty`)

**Comment by aappling-usgs** [comment]
Could you share example contents of `points_attr`? I don't fully understand why you wouldn't just be able to omit NAs and empty strings before passing a list into `render`, e.g.,
```r
list(a=NA, b=1) %>% .[!is.na(.) & .!='']
```

**Comment by jread-usgs** [comment]
`points_attr` is automatically generated if it doesn't exist based on the attributes of the file(s) it is summarizing. Looks something like this if it hasn't been manually updated:

```
points_attr
$attributes
$attributes[[1]]
$attributes[[1]]$`attr-label`
[1] "site_name"

$attributes[[1]]$`attr-def`
[1] "NA"

$attributes[[1]]$`attr-defs`
[1] "NA"

$attributes[[1]]$`data-min`
[1] "NA"

$attributes[[1]]$`data-max`
[1] "NA"

$attributes[[1]]$`data-units`
[1] "NA"
```

**Comment by aappling-usgs** [comment]
OK, thanks. Just be really clear about precedence in the docs.

**Comment by jread-usgs** [comment]
I am going to revert and close this because I agree this is too much of a backdoor (and too dangerous).
