### ISSUE TITLE
create render function

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/meddle#7]
flexible to either point to template that is included in the package by default, or to a file path for a different one. Since we want to include the option to separately specify fields w/o the yaml, I would suggest:

```r
render(config="global.yaml", filename, template, ...)
```
or something along those lines

this function calls `whisker::whisker.render` with a little fancy combining and overwriting fields in global.yaml w/ the `...`s

**Comment by jread-usgs** [comment]
actually, maybe this signature should be 

```r
render(config="global.yaml", ..., template)
```
because template will be the default in most conditions.

**Comment by jread-usgs** [comment]
@berdaniera 

Here is what I am thinking on this
the `template` will be a filepath, and if missing, would default to the one that exists in the package here: 
`system.file(package='meddle','extdata', "FGDC_template.mustache")`

The yaml file that `config` points to is a yaml that contains values for the tags in the template. Those tags in the template (once the file is read in to R) are along the lines of 
`This doc made by: {{author-name}}`, so if the `config` has this kind of content:
```yaml
author-name: "John Doe"
details: "NA"
favorite-animal: "dog"
```
```r
render("global.yaml", filename='metadata.xml')
```
creates `This doc made by: John Doe` in the metadata.xml file
(details and fave animal are ignored because they don't show up in the template tags)

I was thinking that the `...`s would allow you to add to the data used to render, and would overwrite things from the config file. 

so
```r
render("global.yaml", filename='metadata.xml`, list('author-name','Jane Doe')
```
creates `This doc made by: Jane Doe` in the metadata.xml file

What do you think?

**Comment by jread-usgs** [comment]
The `config.yaml` is something the user writes, but maybe there is a function that helps you create a skeleton for it...or there could be one built into the package that helps you start it out.

**Comment by berdaniera** [comment]
Very good @jread-usgs I think I'm getting it! I'll try to get a draft up for you to look at early next week.

**Comment by jread-usgs** [comment]
Sounds good!

**Comment by jread-usgs** [comment]
I think this is good to go for now.
