### ISSUE TITLE
Changing maintainer of Meddle

### ISSUE THREAD

**Issue by msleckman** [USGS-R/meddle#81]
@jordansread since I will be hopefully spending some time this year building on the work you put in to create the meddle package, it would be worth adding/swapping me as a creator/maintainer. 
Can you set that up on your end quickly ? I am not sure if that is something you simply need to update on the [Description ](https://github.com/USGS-R/meddle/blob/d1a4aa288831707b65856995a2d464a399093ad4/DESCRIPTION#L5-L8) Roxygen note or in the repo settings. 

@aappling-usgs @limnoliver this might be something both of you may easily be able to do as well.

**Comment by jordansread** [comment]
@msleckman 👋 briefly weighing in. 

You are admin of this repo and can make this change similar to what we did with geoknife when Blodgett took over as maintainer. See [here](https://github.com/DOI-USGS/geoknife/commit/3268a531731ff4dc8282960aaf09d040a9d546f1)
